# Numpy

## Basic2 

In [1]:
import numpy as np

### Indexing and slicing

In [5]:
data = np.array([1, 2, 3])

In [8]:
print(data[1])

2


In [10]:
print(data[0:2])
print(data[1:])
print(data[-2:])


[1 2]
[2 3]
[2 3]


In [27]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [15]:
print(a[a < 5])

[1 2 3 4]


In [19]:
five_up = (a >=5 )
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [22]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [25]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [26]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [29]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [31]:
b= np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [33]:
list_of_coordinates = list(zip(b[0], b[1]))

In [36]:
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [37]:
print(a[b])

[1 2 3 4]


### How to create an array from existing data

In [39]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [43]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [46]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [49]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [52]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [54]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [56]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [67]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
print(b1)

[1 2 3 4]


In [70]:
b1[0] = 99
print(b1)
print(a)

[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### [Basic array operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)