# Numpy

## Basic3

In [64]:
import numpy as np

### Creating matrices

In [65]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


In [67]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [68]:
data = np.array([[1, 2], 
                 [5, 3], 
                 [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [69]:
print(data.max(axis=0))
print(data.max(axis=1))


[5 6]
[2 5 6]


In [70]:
data = np.array([[1,2], [3, 4]])
ones = np.ones(2, dtype=int)
data + ones

array([[2, 3],
       [4, 5]])

In [71]:
# You can do these arithmetic operations on matrices of different sizes,
# but only if one matrix has only one column or one row. In this case, NumPy will use its broadcast rules for the operation.
data = np.array([[1, 2], 
                 [3, 4], 
                 [5, 6]])
one_row = np.array([[1, 1]])
data + one_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [72]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [73]:
print(np.ones(3))
print(np.zeros(3))
rng = np.random.default_rng()  # the simplest way to generate random numbers
print(rng.random(3))

[1. 1. 1.]
[0. 0. 0.]
[0.62152434 0.84089596 0.4189814 ]


In [74]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(rng.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.85875888 0.00840861]
 [0.65150668 0.60376947]
 [0.16656156 0.43439617]]


### Generating random numbers

In [75]:
rng.integers(5, size=(2, 4))

array([[3, 3, 4, 0],
       [0, 0, 0, 2]])

### How to get unique items and counts

In [76]:
a = np.array([11, 11, 12, 14, 13,15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [77]:
unique_values = np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [78]:
unique_values, indices_list = np.unique(a, return_index=True)
print(unique_values)
print(indices_list)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  3  5  6  7 12 13 14]


In [79]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(unique_values)
print(occurrence_count)


[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]


In [80]:
a_2d = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12], 
                 [1, 2, 3, 4]])

In [81]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [82]:
unique_values = np.unique(a_2d, axis=0)
print(unique_values)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [83]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_index=True, return_counts=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


### Transposing and reshaping a matrix

In [84]:
data = np.array([[1, 2], 
                 [3, 4], 
                 [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
print(data.reshape(2, 3))
print(data.reshape(3, 2))


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [86]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [87]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [88]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array

In [89]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [91]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [92]:
print(np.flip(arr_2d))
print(np.flip(arr_2d, axis=0))
print(np.flip(arr_2d, axis=1))


[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [101]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [110]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


### Reshaping and flattening multidimensional arrays

In [112]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [115]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [118]:
a1 = x.flatten()
a1[0]=99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [120]:
a2 = x.ravel()
a2[0]=98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### How to access the docstring for more information

In [122]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [128]:
max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

In [130]:
len??

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

### Working with mathematical formulas