# Numpy

## Basic

In [5]:
import numpy as np

### 1D Array

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0]

np.int64(1)

In [ ]:
a[0] = 10
a

array([[10, 10, 10, 10],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
b = a[3:]
b[0] = 40
a

array([ 1,  2,  3, 40,  5,  6])

### 2D Array

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[2,2]

np.int64(11)

### Array attributes

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 4)

In [ ]:
len(a.shape) == a.ndim

True

In [ ]:
a.size

12

In [ ]:
import math
a.size == math.prod(a.shape)

True

In [ ]:
a.dtype

dtype('int64')

### How to create a basic array


In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.empty(2)

array([1., 1.])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
# it generates 5 evenly spaced numbers between 0 and 10, inclusive.
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

### Adding, removing, and sorting elements

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [8]:
np.concatenate((a, b))

array([ 1,  2,  3, 40,  5,  6, 40,  5,  6])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### How do you know the shape and size of an array?

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])


In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

### Can you reshape an array?

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

### How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape


(6,)

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
col_vecotr = a[:, np.newaxis]
col_vecotr.shape

(6, 1)

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)