# Numpy

## Basic2 

In [2]:
import numpy as np

### Indexing and slicing

In [3]:
data = np.array([1, 2, 3])

In [4]:
print(data[1])

2


In [5]:
print(data[0:2])
print(data[1:])
print(data[-2:])


[1 2]
[2 3]
[2 3]


In [6]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
print(a[a < 5])

[1 2 3 4]


In [8]:
five_up = (a >=5 )
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [9]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [10]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [11]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [12]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [13]:
b= np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [14]:
list_of_coordinates = list(zip(b[0], b[1]))

In [15]:
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [16]:
print(a[b])

[1 2 3 4]


### How to create an array from existing data

In [17]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [19]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [20]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [21]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [22]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [23]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [24]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [25]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
print(b1)

[1 2 3 4]


In [26]:
b1[0] = 99
print(b1)
print(a)

[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### [Basic array operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)

In [36]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data) 
print(ones)

[1 2]
[1 1]


In [37]:
data + ones

array([2, 3])

In [43]:
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


In [45]:
a = np.array([1, 2, 3, 4])
a.sum()

np.int64(10)

In [58]:
b = np.array([[1, 1, 0], 
              [2, 2, 1],
              [3, 3, 2]])

In [59]:
b.sum(axis=0)

array([6, 6, 3])

In [61]:
b.sum(axis=1)

array([2, 5, 8])

In [65]:
data = np.array([1.0, 2.0])

In [68]:
data * 1.6

array([1.6, 3.2])

###  More useful array operations

In [70]:
data.max()

np.int64(2)

In [71]:
data.min()

np.int64(1)

In [74]:
data.sum()

np.int64(3)

In [76]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [82]:
print(a.sum())
print(a.min())
print(a.max())

4.8595784
0.05093587
0.82485143


In [84]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [85]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])